version: '3.8'

services:
  # Mongodb service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=p1234
      - ME_CONFIG_MONGODB_SERVER=mongodb


  # Node api service
  api:
    build: ./server/
    ports:
      # local->container
      - 3100:3100
    environment:
      PORT: 3100
    depends_on: 
      - mongodb

volumes:
  mongo-data:
    driver: local